/*
	Copyright 2023 Efabless Corp.

	Author: Mohamed Shalan (mshalan@efabless.com)

	This file is auto-generated by wrapper_gen.py on 2023-11-28

	Licensed under the Apache License, Version 2.0 (the "License");
	you may not use this file except in compliance with the License.
	You may obtain a copy of the License at

	    http://www.apache.org/licenses/LICENSE-2.0

	Unless required by applicable law or agreed to in writing, software
	distributed under the License is distributed on an "AS IS" BASIS,
	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	See the License for the specific language governing permissions and
	limitations under the License.

*/


/*! \file EF_ADCS1008A.c
    \brief C source file for the EF_ADCS1008A IP.
    
*/

#ifndef EF_ADCS1008A_C
#define EF_ADCS1008A_C

/******************************************************************************
* Includes
******************************************************************************/

#include "EF_ADCS1008A.h"



EF_DRIVER_STATUS EF_ADCS1008A_setClockDivider(EF_ADCS1008A_TYPE_PTR adc, char value){

    EF_DRIVER_STATUS status = EF_DRIVER_OK;


    if (adc == NULL) {
        status = EF_DRIVER_ERROR_PARAMETER;
    }
    else {
        // Clear the bits at the specified offset in the original number
        adc->TCTRL &= ~(EF_ADCS1008A_TCTRL_REG_CLKDIV_MASK);

        // Set the bits with the given value at the specified offset
        adc->TCTRL |= (value << EF_ADCS1008A_TCTRL_REG_CLKDIV_BIT);
    }

    return status;

}

EF_DRIVER_STATUS EF_ADCS1008A_setSampleDivider(EF_ADCS1008A_TYPE_PTR adc, char value){


    EF_DRIVER_STATUS status = EF_DRIVER_OK;


    if (adc == NULL) {
        status = EF_DRIVER_ERROR_PARAMETER;
    }
    else {
        // Clear the bits at the specified offset in the original number
        adc->TCTRL &= ~EF_ADCS1008A_TCTRL_REG_SAMPLE_DIV_MASK;

        // Set the bits with the given value at the specified offset
        adc->TCTRL |= (value << EF_ADCS1008A_TCTRL_REG_SAMPLE_DIV_BIT);

    }
    return status;
}

EF_DRIVER_STATUS EF_ADCS1008A_setTimerCtrlReg(EF_ADCS1008A_TYPE_PTR adc, uint32_t mask){

    EF_DRIVER_STATUS status = EF_DRIVER_OK;


    if (adc == NULL) {
        status = EF_DRIVER_ERROR_PARAMETER;
    }
    else {
        adc->TCTRL = mask;
    }

    return status;

}

EF_DRIVER_STATUS EF_ADCS1008A_getTimerCtrlReg(EF_ADCS1008A_TYPE_PTR adc, uint32_t *ctrl_value){
    EF_DRIVER_STATUS status = EF_DRIVER_OK;


    if (adc == NULL || ctrl_value == NULL) {
        status = EF_DRIVER_ERROR_PARAMETER;
    }
    else {
        *ctrl_value = adc->TCTRL;
    }

    return status;
}



EF_DRIVER_STATUS EF_ADCS1008A_setChannelNumber (EF_ADCS1008A_TYPE_PTR adc, uint32_t mask){

    EF_DRIVER_STATUS status = EF_DRIVER_OK;


    if (adc == NULL) {
        status = EF_DRIVER_ERROR_PARAMETER;
    }
    else {
        adc->CHSEL = mask;
    }

    return status;

}

EF_DRIVER_STATUS EF_ADCS1008A_getChannelNumber (EF_ADCS1008A_TYPE_PTR adc, uint32_t *channel_number){

    EF_DRIVER_STATUS status = EF_DRIVER_OK;


    if (adc == NULL || channel_number == NULL) {
        status = EF_DRIVER_ERROR_PARAMETER;
    }
    else {
        *channel_number = adc->CHSEL;
    }

    return status;

}

EF_DRIVER_STATUS EF_ADCS1008A_enable (EF_ADCS1008A_TYPE_PTR adc, bool enable){

    EF_DRIVER_STATUS status = EF_DRIVER_OK;


    if (adc == NULL) {
        status = EF_DRIVER_ERROR_PARAMETER;
    }
    else {
        if(enable){
            adc->CTRL |= EF_ADCS1008A_CTRL_REG_EN_MASK; 
        }
        else {

            adc->CTRL &= ~(EF_ADCS1008A_CTRL_REG_EN_MASK); 
        }
    }
    return status;
}

EF_DRIVER_STATUS EF_ADCS1008A_sequencerEnable (EF_ADCS1008A_TYPE_PTR adc, bool enable){
    
    EF_DRIVER_STATUS status = EF_DRIVER_OK;


    if (adc == NULL) {
        status = EF_DRIVER_ERROR_PARAMETER;
    }
    else {
        if(enable){
            adc->CTRL |= EF_ADCS1008A_CTRL_REG_SEQEN_MASK; 
        }
        else {

            adc->CTRL &= ~(EF_ADCS1008A_CTRL_REG_SEQEN_MASK); 
        }
    }
    return status;
}

EF_DRIVER_STATUS EF_ADCS1008A_setCtrlReg(EF_ADCS1008A_TYPE_PTR adc, uint32_t mask){
    
    EF_DRIVER_STATUS status = EF_DRIVER_OK;


    if (adc == NULL) {
        status = EF_DRIVER_ERROR_PARAMETER;
    }
    else {
        adc->CTRL = mask;
    }
    
    return status;
}

EF_DRIVER_STATUS EF_ADCS1008A_getCtrlReg (EF_ADCS1008A_TYPE_PTR adc, uint32_t *ctrl_value){ 

    EF_DRIVER_STATUS status = EF_DRIVER_OK;


    if (adc == NULL || ctrl_value == NULL) {
        status = EF_DRIVER_ERROR_PARAMETER;
    }
    else {
        *ctrl_value = adc->CTRL;
    }

    return status;


}

EF_DRIVER_STATUS EF_ADCS1008A_setStartConversion (EF_ADCS1008A_TYPE_PTR adc, bool start){

    EF_DRIVER_STATUS status = EF_DRIVER_OK;


    if (adc == NULL) {
        status = EF_DRIVER_ERROR_PARAMETER;
    }
    else {
        if(start){
            adc->SOC |= EF_ADCS1008A_SOC_REG_SOC_MASK;
        }
        else {
            adc->SOC &= ~(EF_ADCS1008A_SOC_REG_SOC_MASK);
        }
    }
    return status;
}

EF_DRIVER_STATUS EF_ADCS1008A_getStartConversion (EF_ADCS1008A_TYPE_PTR adc, uint32_t *value){

    EF_DRIVER_STATUS status = EF_DRIVER_OK;


    if (adc == NULL || value == NULL) {
        status = EF_DRIVER_ERROR_PARAMETER;
    }
    else {
        *value = adc->SOC;
    }
    return status;

}

EF_DRIVER_STATUS EF_ADCS1008A_setStep0 (EF_ADCS1008A_TYPE_PTR adc, uint32_t value){

    EF_DRIVER_STATUS status = EF_DRIVER_OK;

    if (adc == NULL) {
        status = EF_DRIVER_ERROR_PARAMETER;
    }
    else {

        // Clear the bits at the specified offset in the original number
        adc->SEQCTRL0 &= ~EF_ADCS1008A_SEQCTRL0_REG_SEQ0_MASK;

        // Set the bits with the given value at the specified offset
        adc->SEQCTRL0 |= (value << EF_ADCS1008A_SEQCTRL0_REG_SEQ0_BIT);

    }
    return status;

}
EF_DRIVER_STATUS EF_ADCS1008A_setStep1 (EF_ADCS1008A_TYPE_PTR adc, uint32_t value){

    EF_DRIVER_STATUS status = EF_DRIVER_OK;

    if (adc == NULL) {
        status = EF_DRIVER_ERROR_PARAMETER;
    }
    else {


        // Clear the bits at the specified offset in the original number
        adc->SEQCTRL0 &= ~EF_ADCS1008A_SEQCTRL0_REG_SEQ1_MASK;

        // Set the bits with the given value at the specified offset
        adc->SEQCTRL0 |= (value << EF_ADCS1008A_SEQCTRL0_REG_SEQ1_BIT);

    }
    return status;


}

EF_DRIVER_STATUS EF_ADCS1008A_setStep2 (EF_ADCS1008A_TYPE_PTR adc, uint32_t value){
    EF_DRIVER_STATUS status = EF_DRIVER_OK;

    if (adc == NULL) {
        status = EF_DRIVER_ERROR_PARAMETER;
    }
    else {

        // Clear the bits at the specified offset in the original number
        adc->SEQCTRL0 &= ~EF_ADCS1008A_SEQCTRL0_REG_SEQ2_MASK;

        // Set the bits with the given value at the specified offset
        adc->SEQCTRL0 |= (value << EF_ADCS1008A_SEQCTRL0_REG_SEQ2_BIT);
    }
    return status;

}

EF_DRIVER_STATUS EF_ADCS1008A_setStep3 (EF_ADCS1008A_TYPE_PTR adc, uint32_t value){

    EF_DRIVER_STATUS status = EF_DRIVER_OK;

    if (adc == NULL) {
        status = EF_DRIVER_ERROR_PARAMETER;
    }
    else {

        // Clear the bits at the specified offset in the original number
        adc->SEQCTRL0 &= ~EF_ADCS1008A_SEQCTRL0_REG_SEQ3_MASK;

        // Set the bits with the given value at the specified offset
        adc->SEQCTRL0 |= (value << EF_ADCS1008A_SEQCTRL0_REG_SEQ3_BIT);
    }
    return status;
}

EF_DRIVER_STATUS EF_ADCS1008A_setSeqCtrlReg0 (EF_ADCS1008A_TYPE_PTR adc, uint32_t value){

    EF_DRIVER_STATUS status = EF_DRIVER_OK;

    if (adc == NULL) {
        status = EF_DRIVER_ERROR_PARAMETER;
    }
    else {
        adc->SEQCTRL0 = value;
    }
    return status;
}

EF_DRIVER_STATUS EF_ADCS1008A_getSeqCtrlReg0 (EF_ADCS1008A_TYPE_PTR adc, uint32_t *seq_ctrl_value){

    EF_DRIVER_STATUS status = EF_DRIVER_OK;


    if (adc == NULL || seq_ctrl_value == NULL) {
        status = EF_DRIVER_ERROR_PARAMETER;
    }
    else {
        *seq_ctrl_value = adc->SEQCTRL0;
    }
    return status;


}

EF_DRIVER_STATUS EF_ADCS1008A_setStep4 (EF_ADCS1008A_TYPE_PTR adc, uint32_t value){

    EF_DRIVER_STATUS status = EF_DRIVER_OK;

    if (adc == NULL) {
        status = EF_DRIVER_ERROR_PARAMETER;
    }
    else {

        // Clear the bits at the specified offset in the original number
        adc->SEQCTRL1 &= ~EF_ADCS1008A_SEQCTRL1_REG_SEQ4_MASK;

        // Set the bits with the given value at the specified offset
        adc->SEQCTRL1 |= (value << EF_ADCS1008A_SEQCTRL1_REG_SEQ4_BIT);
    }
    return status;

}

EF_DRIVER_STATUS EF_ADCS1008A_setStep5 (EF_ADCS1008A_TYPE_PTR adc, uint32_t value){
    EF_DRIVER_STATUS status = EF_DRIVER_OK;

    if (adc == NULL) {
        status = EF_DRIVER_ERROR_PARAMETER;
    }
    else {

        // Clear the bits at the specified offset in the original number
        adc->SEQCTRL1 &= ~EF_ADCS1008A_SEQCTRL1_REG_SEQ5_MASK;

        // Set the bits with the given value at the specified offset
        adc->SEQCTRL1 |= (value << EF_ADCS1008A_SEQCTRL1_REG_SEQ5_BIT);
    }
    return status;

}

EF_DRIVER_STATUS EF_ADCS1008A_setStep6 (EF_ADCS1008A_TYPE_PTR adc, uint32_t value){

    EF_DRIVER_STATUS status = EF_DRIVER_OK;

    if (adc == NULL) {
        status = EF_DRIVER_ERROR_PARAMETER;
    }
    else {

        // Clear the bits at the specified offset in the original number
        adc->SEQCTRL1 &= ~EF_ADCS1008A_SEQCTRL1_REG_SEQ6_MASK;

        // Set the bits with the given value at the specified offset
        adc->SEQCTRL1 |= (value << EF_ADCS1008A_SEQCTRL1_REG_SEQ6_BIT);
    }
    return status;

}

EF_DRIVER_STATUS EF_ADCS1008A_setStep7 (EF_ADCS1008A_TYPE_PTR adc, uint32_t value){

    EF_DRIVER_STATUS status = EF_DRIVER_OK;

    if (adc == NULL) {
        status = EF_DRIVER_ERROR_PARAMETER;
    }
    else {

        // Clear the bits at the specified offset in the original number
        adc->SEQCTRL1 &= ~EF_ADCS1008A_SEQCTRL1_REG_SEQ7_MASK;

        // Set the bits with the given value at the specified offset
        adc->SEQCTRL1 |= (value << EF_ADCS1008A_SEQCTRL1_REG_SEQ7_BIT);
    }
    return status;

}

EF_DRIVER_STATUS EF_ADCS1008A_setSeqCtrlReg1 (EF_ADCS1008A_TYPE_PTR adc, uint32_t value){

    EF_DRIVER_STATUS status = EF_DRIVER_OK;

    if (adc == NULL) {
        status = EF_DRIVER_ERROR_PARAMETER;
    }
    else {
        adc->SEQCTRL1 = value;
    }
    return status;
}


EF_DRIVER_STATUS EF_ADCS1008A_getSeqCtrlReg1 (EF_ADCS1008A_TYPE_PTR adc, uint32_t *seq_ctrl_value){

    EF_DRIVER_STATUS status = EF_DRIVER_OK;


    if (adc == NULL || seq_ctrl_value == NULL) {
        status = EF_DRIVER_ERROR_PARAMETER;
    }
    else {
        *seq_ctrl_value = adc->SEQCTRL1;
    }
    return status;

}

EF_DRIVER_STATUS EF_ADCS1008A_getDataReg (EF_ADCS1008A_TYPE_PTR adc, uint32_t *data){

    EF_DRIVER_STATUS status = EF_DRIVER_OK;


    if (adc == NULL || data == NULL) {
        status = EF_DRIVER_ERROR_PARAMETER;
    }
    else {
        *data = adc->DATA;
    }
    return status;

}

EF_DRIVER_STATUS EF_ADCS1008A_setFIFOlevel (EF_ADCS1008A_TYPE_PTR adc, uint32_t value){

    EF_DRIVER_STATUS status = EF_DRIVER_OK;

    if (adc == NULL) {
        status = EF_DRIVER_ERROR_PARAMETER;
    }
    else {
        adc->FIFOLEVEL = value;
    }
    return status;

}

EF_DRIVER_STATUS EF_ADCS1008A_getFIFOlevel (EF_ADCS1008A_TYPE_PTR adc, uint32_t *fifo_level){

    EF_DRIVER_STATUS status = EF_DRIVER_OK;

    if (adc == NULL || fifo_level == NULL) {
        status = EF_DRIVER_ERROR_PARAMETER;
    }
    else {
        *fifo_level = adc->FIFOLEVEL;
    }
    return status;
}


EF_DRIVER_STATUS EF_ADCS1008A_getRIS (EF_ADCS1008A_TYPE_PTR adc, uint32_t *ris){

    EF_DRIVER_STATUS status = EF_DRIVER_OK;

    if (adc == NULL || ris == NULL) {
        status = EF_DRIVER_ERROR_PARAMETER;
    }
    else {
        *ris = adc->RIS;
    }
    return status;

}

EF_DRIVER_STATUS EF_ADCS1008A_getMIS (EF_ADCS1008A_TYPE_PTR adc, uint32_t *mis){

    EF_DRIVER_STATUS status = EF_DRIVER_OK;

    if (adc == NULL || mis == NULL) {
        status = EF_DRIVER_ERROR_PARAMETER;
    }
    else {
        *mis = adc->MIS;
    }
    return status;
}

EF_DRIVER_STATUS EF_ADCS1008A_setIM (EF_ADCS1008A_TYPE_PTR adc, uint32_t value){

    EF_DRIVER_STATUS status = EF_DRIVER_OK;

    if (adc == NULL) {
        status = EF_DRIVER_ERROR_PARAMETER;
    }
    else {
        adc->IM = value;
    }
    return status;

}

EF_DRIVER_STATUS EF_ADCS1008A_getIM (EF_ADCS1008A_TYPE_PTR adc, uint32_t *im){

    EF_DRIVER_STATUS status = EF_DRIVER_OK;

    if (adc == NULL || im == NULL) {
        status = EF_DRIVER_ERROR_PARAMETER;
    }
    else {
        *im = adc->IM;
    }
    return status;

}

EF_DRIVER_STATUS EF_ADCS1008A_setIC (EF_ADCS1008A_TYPE_PTR adc, uint32_t value) {

    EF_DRIVER_STATUS status = EF_DRIVER_OK;

    if (adc == NULL) {
        status = EF_DRIVER_ERROR_PARAMETER;
    }
    else {
        adc->IC = value;
    }
    return status;
}


#endif