
/*
	Copyright 2023 Efabless Corp.

	Author: Mohamed Shalan (mshalan@efabless.com)

	This file is auto-generated by wrapper_gen.py

	Licensed under the Apache License, Version 2.0 (the "License");
	you may not use this file except in compliance with the License.
	You may obtain a copy of the License at

	    http://www.apache.org/licenses/LICENSE-2.0

	Unless required by applicable law or agreed to in writing, software
	distributed under the License is distributed on an "AS IS" BASIS,
	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	See the License for the specific language governing permissions and
	limitations under the License.

*/


#define ADC0_BASE				0x00000000

#define	ADC0_TCTRL_REG_ADDR		(ADC0_BASE+0x0)
#define	ADC0_CHSEL_REG_ADDR		(ADC0_BASE+0x4)
#define	ADC0_CTRL_REG_ADDR		(ADC0_BASE+0x8)
#define	ADC0_SOC_REG_ADDR		(ADC0_BASE+0xc)
#define	ADC0_SEQCTRL0_REG_ADDR		(ADC0_BASE+0x10)
#define	ADC0_SEQCTRL1_REG_ADDR		(ADC0_BASE+0x14)
#define	ADC0_DATA_REG_ADDR		(ADC0_BASE+0x18)
#define	ADC0_FIFOLEVEL_REG_ADDR		(ADC0_BASE+0x1c)
#define	ADC0_ICR_REG_ADDR		(ADC0_BASE+0xf00)
#define	ADC0_RIS_REG_ADDR		(ADC0_BASE+0xf04)
#define	ADC0_IM_REG_ADDR		(ADC0_BASE+0xf08)
#define	ADC0_MIS_REG_ADDR		(ADC0_BASE+0xf0c)

#define ADC0_TCTRL_REG_CLKDIV		0
#define ADC0_TCTRL_REG_CLKDIV_LEN	8
#define ADC0_TCTRL_REG_SAMPLE_DIV		8
#define ADC0_TCTRL_REG_SAMPLE_DIV_LEN	8
#define ADC0_TCTRL_REG_SWIDTH		16
#define ADC0_TCTRL_REG_SWIDTH_LEN	4
#define ADC0_CHSEL_REG_CHANNEL		0
#define ADC0_CHSEL_REG_CHANNEL_LEN	3
#define ADC0_CTRL_REG_EN		0
#define ADC0_CTRL_REG_EN_LEN	1
#define ADC0_CTRL_REG_SEQEN		1
#define ADC0_CTRL_REG_SEQEN_LEN	1
#define ADC0_SOC_REG_SOC		0
#define ADC0_SOC_REG_SOC_LEN	1
#define ADC0_SEQCTRL0_REG_SEQ0		0
#define ADC0_SEQCTRL0_REG_SEQ0_LEN	5
#define ADC0_SEQCTRL0_REG_SEQ1		8
#define ADC0_SEQCTRL0_REG_SEQ1_LEN	5
#define ADC0_SEQCTRL0_REG_SEQ2		16
#define ADC0_SEQCTRL0_REG_SEQ2_LEN	5
#define ADC0_SEQCTRL0_REG_SEQ3		24
#define ADC0_SEQCTRL0_REG_SEQ3_LEN	5
#define ADC0_SEQCTRL1_REG_SEQ4		0
#define ADC0_SEQCTRL1_REG_SEQ4_LEN	5
#define ADC0_SEQCTRL1_REG_SEQ5		8
#define ADC0_SEQCTRL1_REG_SEQ5_LEN	5
#define ADC0_SEQCTRL1_REG_SEQ6		16
#define ADC0_SEQCTRL1_REG_SEQ6_LEN	5
#define ADC0_SEQCTRL1_REG_SEQ7		24
#define ADC0_SEQCTRL1_REG_SEQ7_LEN	5
#define ADC0_DATA_REG_DATA		0
#define ADC0_DATA_REG_DATA_LEN	10
#define ADC0_FIFOLEVEL_REG_VALUE		0
#define ADC0_FIFOLEVEL_REG_VALUE_LEN	5
#define INT_FIFO_FULL_FLAG	0x1
#define INT_FIFO_LEVEL_FLAG	0x2
#define INT_EOC_FLAG	0x4

volatile unsigned int * adc0_TCTRL	= (volatile unsigned int *) ADC0_TCTRL_REG_ADDR;
volatile unsigned int * adc0_CHSEL	= (volatile unsigned int *) ADC0_CHSEL_REG_ADDR;
volatile unsigned int * adc0_CTRL	= (volatile unsigned int *) ADC0_CTRL_REG_ADDR;
volatile unsigned int * adc0_SOC	= (volatile unsigned int *) ADC0_SOC_REG_ADDR;
volatile unsigned int * adc0_SEQCTRL0	= (volatile unsigned int *) ADC0_SEQCTRL0_REG_ADDR;
volatile unsigned int * adc0_SEQCTRL1	= (volatile unsigned int *) ADC0_SEQCTRL1_REG_ADDR;
volatile unsigned int * adc0_DATA	= (volatile unsigned int *) ADC0_DATA_REG_ADDR;
volatile unsigned int * adc0_FIFOLEVEL	= (volatile unsigned int *) ADC0_FIFOLEVEL_REG_ADDR;
